import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Register fonts (optional, using standard fonts for now)
// Font.register({ family: 'Roboto', src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf' });

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 40,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#10B981', // Resilience Green
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    subtitle: {
        fontSize: 14,
        color: '#6B7280',
        marginTop: 5,
    },
    section: {
        margin: 10,
        padding: 10,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#10B981',
    },
    text: {
        fontSize: 12,
        marginBottom: 5,
        lineHeight: 1.5,
        color: '#374151',
    },
    scoreRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 5,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        paddingBottom: 5,
    },
    scoreLabel: {
        fontSize: 12,
        fontWeight: 'bold',
    },
    scoreValue: {
        fontSize: 12,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        color: '#9CA3AF',
        fontSize: 10,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        paddingTop: 10,
    },
});

interface AssessmentReportProps {
    data: {
        facilityName?: string;
        date?: string;
        overallScore?: number;
        pillarScores?: Record<string, number>;
    };
}

export const AssessmentReport = ({ data }: AssessmentReportProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            {/* Header */}
            <View style={styles.header}>
                <Text style={styles.title}>Pathways Health Assessment</Text>
                <Text style={styles.subtitle}>Climate Resilience Report</Text>
            </View>

            {/* Facility Info */}
            <View style={styles.section}>
                <Text style={styles.text}>Facility Name: {data.facilityName || 'Unknown Facility'}</Text>
                <Text style={styles.text}>Date: {data.date ? new Date(data.date).toLocaleDateString() : new Date().toLocaleDateString()}</Text>
            </View>

            {/* Executive Summary */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Executive Summary</Text>
                <Text style={styles.text}>
                    This report provides a summary of your facility's climate resilience assessment.
                    Your overall resilience score is {data.overallScore}/100.
                </Text>
            </View>

            {/* Pillar Scores */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Pillar Scores</Text>
                {data.pillarScores && Object.entries(data.pillarScores).map(([pillar, score]) => (
                    <View key={pillar} style={styles.scoreRow}>
                        <Text style={styles.scoreLabel}>{pillar}</Text>
                        <Text style={styles.scoreValue}>{score}%</Text>
                    </View>
                ))}
            </View>

            {/* Priority Actions (Placeholder) */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Priority Actions</Text>
                <Text style={styles.text}>1. Conduct a detailed flood risk assessment.</Text>
                <Text style={styles.text}>2. Install backup power generators for critical areas.</Text>
                <Text style={styles.text}>3. Develop a water conservation plan.</Text>
            </View>

            {/* Footer */}
            <View style={styles.footer}>
                <Text>Generated by Pathways Health - Empowering Healthcare Resilience</Text>
            </View>
        </Page>
    </Document>
);
